/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedApotekerRouteImport } from './routes/_authenticated/apoteker'
import { Route as AuthenticatedPasienRouteImport } from './routes/_authenticated/pasien'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as AuthenticatedAdminObatRouteImport } from './routes/_authenticated/admin.obat'
import { Route as AuthenticatedAdminSkriningRouteImport } from './routes/_authenticated/admin.skrining'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedApotekerIndexRouteImport } from './routes/_authenticated/apoteker.index'
import { Route as AuthenticatedApotekerEdukasiRouteImport } from './routes/_authenticated/apoteker.edukasi'
import { Route as AuthenticatedApotekerKepatuhanRouteImport } from './routes/_authenticated/apoteker.kepatuhan'
import { Route as AuthenticatedApotekerKonsultasiRouteImport } from './routes/_authenticated/apoteker.konsultasi'
import { Route as AuthenticatedApotekerObatRouteImport } from './routes/_authenticated/apoteker.obat'
import { Route as AuthenticatedApotekerPasienRouteImport } from './routes/_authenticated/apoteker.pasien'
import { Route as AuthenticatedPasienIndexRouteImport } from './routes/_authenticated/pasien.index'
import { Route as AuthenticatedPasienCatatRouteImport } from './routes/_authenticated/pasien.catat'
import { Route as AuthenticatedPasienEdukasiRouteImport } from './routes/_authenticated/pasien.edukasi'
import { Route as AuthenticatedPasienKonsultasiRouteImport } from './routes/_authenticated/pasien.konsultasi'
import { Route as AuthenticatedPasienLogbookRouteImport } from './routes/_authenticated/pasien.logbook'
import { Route as AuthenticatedPasienObatRouteImport } from './routes/_authenticated/pasien.obat'
import { Route as AuthenticatedPasienProfilRouteImport } from './routes/_authenticated/pasien.profil'
import { Route as AuthenticatedPasienRiwayatRouteImport } from './routes/_authenticated/pasien.riwayat'
import { Route as ApiPublicProvisionAccountsRouteImport } from './routes/api/public/provision-accounts'
import { Route as AuthenticatedAdminBackupRiwayatRouteImport } from './routes/_authenticated/admin.backup.riwayat'
import { Route as AuthenticatedAdminPasienSkriningIdRouteImport } from './routes/_authenticated/admin.pasien-skrining.$id'
import { Route as AuthenticatedApotekerPasienIdRouteImport } from './routes/_authenticated/apoteker.pasien.$id'
import { Route as ApiPublicHooksAutoBackupRouteImport } from './routes/api/public/hooks/auto-backup'
import { Route as ApiPublicHooksMarkMissedRouteImport } from './routes/api/public/hooks/mark-missed'
import { Route as ApiPublicHooksMedicationRemindersRouteImport } from './routes/api/public/hooks/medication-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApotekerRoute = AuthenticatedApotekerRouteImport.update({
  id: '/apoteker',
  path: '/apoteker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPasienRoute = AuthenticatedPasienRouteImport.update({
  id: '/pasien',
  path: '/pasien',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminObatRoute = AuthenticatedAdminObatRouteImport.update({
  id: '/obat',
  path: '/obat',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSkriningRoute =
  AuthenticatedAdminSkriningRouteImport.update({
    id: '/skrining',
    path: '/skrining',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedApotekerIndexRoute =
  AuthenticatedApotekerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedApotekerRoute,
  } as any)
const AuthenticatedApotekerEdukasiRoute =
  AuthenticatedApotekerEdukasiRouteImport.update({
    id: '/edukasi',
    path: '/edukasi',
    getParentRoute: () => AuthenticatedApotekerRoute,
  } as any)
const AuthenticatedApotekerKepatuhanRoute =
  AuthenticatedApotekerKepatuhanRouteImport.update({
    id: '/kepatuhan',
    path: '/kepatuhan',
    getParentRoute: () => AuthenticatedApotekerRoute,
  } as any)
const AuthenticatedApotekerKonsultasiRoute =
  AuthenticatedApotekerKonsultasiRouteImport.update({
    id: '/konsultasi',
    path: '/konsultasi',
    getParentRoute: () => AuthenticatedApotekerRoute,
  } as any)
const AuthenticatedApotekerObatRoute =
  AuthenticatedApotekerObatRouteImport.update({
    id: '/obat',
    path: '/obat',
    getParentRoute: () => AuthenticatedApotekerRoute,
  } as any)
const AuthenticatedApotekerPasienRoute =
  AuthenticatedApotekerPasienRouteImport.update({
    id: '/pasien',
    path: '/pasien',
    getParentRoute: () => AuthenticatedApotekerRoute,
  } as any)
const AuthenticatedPasienIndexRoute =
  AuthenticatedPasienIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPasienRoute,
  } as any)
const AuthenticatedPasienCatatRoute =
  AuthenticatedPasienCatatRouteImport.update({
    id: '/catat',
    path: '/catat',
    getParentRoute: () => AuthenticatedPasienRoute,
  } as any)
const AuthenticatedPasienEdukasiRoute =
  AuthenticatedPasienEdukasiRouteImport.update({
    id: '/edukasi',
    path: '/edukasi',
    getParentRoute: () => AuthenticatedPasienRoute,
  } as any)
const AuthenticatedPasienKonsultasiRoute =
  AuthenticatedPasienKonsultasiRouteImport.update({
    id: '/konsultasi',
    path: '/konsultasi',
    getParentRoute: () => AuthenticatedPasienRoute,
  } as any)
const AuthenticatedPasienLogbookRoute =
  AuthenticatedPasienLogbookRouteImport.update({
    id: '/logbook',
    path: '/logbook',
    getParentRoute: () => AuthenticatedPasienRoute,
  } as any)
const AuthenticatedPasienObatRoute = AuthenticatedPasienObatRouteImport.update({
  id: '/obat',
  path: '/obat',
  getParentRoute: () => AuthenticatedPasienRoute,
} as any)
const AuthenticatedPasienProfilRoute =
  AuthenticatedPasienProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedPasienRoute,
  } as any)
const AuthenticatedPasienRiwayatRoute =
  AuthenticatedPasienRiwayatRouteImport.update({
    id: '/riwayat',
    path: '/riwayat',
    getParentRoute: () => AuthenticatedPasienRoute,
  } as any)
const ApiPublicProvisionAccountsRoute =
  ApiPublicProvisionAccountsRouteImport.update({
    id: '/api/public/provision-accounts',
    path: '/api/public/provision-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminBackupRiwayatRoute =
  AuthenticatedAdminBackupRiwayatRouteImport.update({
    id: '/riwayat',
    path: '/riwayat',
    getParentRoute: () => AuthenticatedAdminBackupRoute,
  } as any)
const AuthenticatedAdminPasienSkriningIdRoute =
  AuthenticatedAdminPasienSkriningIdRouteImport.update({
    id: '/pasien-skrining/$id',
    path: '/pasien-skrining/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedApotekerPasienIdRoute =
  AuthenticatedApotekerPasienIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedApotekerPasienRoute,
  } as any)
const ApiPublicHooksAutoBackupRoute =
  ApiPublicHooksAutoBackupRouteImport.update({
    id: '/api/public/hooks/auto-backup',
    path: '/api/public/hooks/auto-backup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMarkMissedRoute =
  ApiPublicHooksMarkMissedRouteImport.update({
    id: '/api/public/hooks/mark-missed',
    path: '/api/public/hooks/mark-missed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMedicationRemindersRoute =
  ApiPublicHooksMedicationRemindersRouteImport.update({
    id: '/api/public/hooks/medication-reminders',
    path: '/api/public/hooks/medication-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/apoteker': typeof AuthenticatedApotekerRouteWithChildren
  '/pasien': typeof AuthenticatedPasienRouteWithChildren
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRouteWithChildren
  '/admin/obat': typeof AuthenticatedAdminObatRoute
  '/admin/skrining': typeof AuthenticatedAdminSkriningRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/apoteker/edukasi': typeof AuthenticatedApotekerEdukasiRoute
  '/apoteker/kepatuhan': typeof AuthenticatedApotekerKepatuhanRoute
  '/apoteker/konsultasi': typeof AuthenticatedApotekerKonsultasiRoute
  '/apoteker/obat': typeof AuthenticatedApotekerObatRoute
  '/apoteker/pasien': typeof AuthenticatedApotekerPasienRouteWithChildren
  '/pasien/catat': typeof AuthenticatedPasienCatatRoute
  '/pasien/edukasi': typeof AuthenticatedPasienEdukasiRoute
  '/pasien/konsultasi': typeof AuthenticatedPasienKonsultasiRoute
  '/pasien/logbook': typeof AuthenticatedPasienLogbookRoute
  '/pasien/obat': typeof AuthenticatedPasienObatRoute
  '/pasien/profil': typeof AuthenticatedPasienProfilRoute
  '/pasien/riwayat': typeof AuthenticatedPasienRiwayatRoute
  '/api/public/provision-accounts': typeof ApiPublicProvisionAccountsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/apoteker/': typeof AuthenticatedApotekerIndexRoute
  '/pasien/': typeof AuthenticatedPasienIndexRoute
  '/admin/backup/riwayat': typeof AuthenticatedAdminBackupRiwayatRoute
  '/admin/pasien-skrining/$id': typeof AuthenticatedAdminPasienSkriningIdRoute
  '/apoteker/pasien/$id': typeof AuthenticatedApotekerPasienIdRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
  '/api/public/hooks/mark-missed': typeof ApiPublicHooksMarkMissedRoute
  '/api/public/hooks/medication-reminders': typeof ApiPublicHooksMedicationRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRouteWithChildren
  '/admin/obat': typeof AuthenticatedAdminObatRoute
  '/admin/skrining': typeof AuthenticatedAdminSkriningRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/apoteker/edukasi': typeof AuthenticatedApotekerEdukasiRoute
  '/apoteker/kepatuhan': typeof AuthenticatedApotekerKepatuhanRoute
  '/apoteker/konsultasi': typeof AuthenticatedApotekerKonsultasiRoute
  '/apoteker/obat': typeof AuthenticatedApotekerObatRoute
  '/apoteker/pasien': typeof AuthenticatedApotekerPasienRouteWithChildren
  '/pasien/catat': typeof AuthenticatedPasienCatatRoute
  '/pasien/edukasi': typeof AuthenticatedPasienEdukasiRoute
  '/pasien/konsultasi': typeof AuthenticatedPasienKonsultasiRoute
  '/pasien/logbook': typeof AuthenticatedPasienLogbookRoute
  '/pasien/obat': typeof AuthenticatedPasienObatRoute
  '/pasien/profil': typeof AuthenticatedPasienProfilRoute
  '/pasien/riwayat': typeof AuthenticatedPasienRiwayatRoute
  '/api/public/provision-accounts': typeof ApiPublicProvisionAccountsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/apoteker': typeof AuthenticatedApotekerIndexRoute
  '/pasien': typeof AuthenticatedPasienIndexRoute
  '/admin/backup/riwayat': typeof AuthenticatedAdminBackupRiwayatRoute
  '/admin/pasien-skrining/$id': typeof AuthenticatedAdminPasienSkriningIdRoute
  '/apoteker/pasien/$id': typeof AuthenticatedApotekerPasienIdRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
  '/api/public/hooks/mark-missed': typeof ApiPublicHooksMarkMissedRoute
  '/api/public/hooks/medication-reminders': typeof ApiPublicHooksMedicationRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/apoteker': typeof AuthenticatedApotekerRouteWithChildren
  '/_authenticated/pasien': typeof AuthenticatedPasienRouteWithChildren
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRouteWithChildren
  '/_authenticated/admin/obat': typeof AuthenticatedAdminObatRoute
  '/_authenticated/admin/skrining': typeof AuthenticatedAdminSkriningRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/apoteker/edukasi': typeof AuthenticatedApotekerEdukasiRoute
  '/_authenticated/apoteker/kepatuhan': typeof AuthenticatedApotekerKepatuhanRoute
  '/_authenticated/apoteker/konsultasi': typeof AuthenticatedApotekerKonsultasiRoute
  '/_authenticated/apoteker/obat': typeof AuthenticatedApotekerObatRoute
  '/_authenticated/apoteker/pasien': typeof AuthenticatedApotekerPasienRouteWithChildren
  '/_authenticated/pasien/catat': typeof AuthenticatedPasienCatatRoute
  '/_authenticated/pasien/edukasi': typeof AuthenticatedPasienEdukasiRoute
  '/_authenticated/pasien/konsultasi': typeof AuthenticatedPasienKonsultasiRoute
  '/_authenticated/pasien/logbook': typeof AuthenticatedPasienLogbookRoute
  '/_authenticated/pasien/obat': typeof AuthenticatedPasienObatRoute
  '/_authenticated/pasien/profil': typeof AuthenticatedPasienProfilRoute
  '/_authenticated/pasien/riwayat': typeof AuthenticatedPasienRiwayatRoute
  '/api/public/provision-accounts': typeof ApiPublicProvisionAccountsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/apoteker/': typeof AuthenticatedApotekerIndexRoute
  '/_authenticated/pasien/': typeof AuthenticatedPasienIndexRoute
  '/_authenticated/admin/backup/riwayat': typeof AuthenticatedAdminBackupRiwayatRoute
  '/_authenticated/admin/pasien-skrining/$id': typeof AuthenticatedAdminPasienSkriningIdRoute
  '/_authenticated/apoteker/pasien/$id': typeof AuthenticatedApotekerPasienIdRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
  '/api/public/hooks/mark-missed': typeof ApiPublicHooksMarkMissedRoute
  '/api/public/hooks/medication-reminders': typeof ApiPublicHooksMedicationRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/apoteker'
    | '/pasien'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/obat'
    | '/admin/skrining'
    | '/admin/users'
    | '/apoteker/edukasi'
    | '/apoteker/kepatuhan'
    | '/apoteker/konsultasi'
    | '/apoteker/obat'
    | '/apoteker/pasien'
    | '/pasien/catat'
    | '/pasien/edukasi'
    | '/pasien/konsultasi'
    | '/pasien/logbook'
    | '/pasien/obat'
    | '/pasien/profil'
    | '/pasien/riwayat'
    | '/api/public/provision-accounts'
    | '/admin/'
    | '/apoteker/'
    | '/pasien/'
    | '/admin/backup/riwayat'
    | '/admin/pasien-skrining/$id'
    | '/apoteker/pasien/$id'
    | '/api/public/hooks/auto-backup'
    | '/api/public/hooks/mark-missed'
    | '/api/public/hooks/medication-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/obat'
    | '/admin/skrining'
    | '/admin/users'
    | '/apoteker/edukasi'
    | '/apoteker/kepatuhan'
    | '/apoteker/konsultasi'
    | '/apoteker/obat'
    | '/apoteker/pasien'
    | '/pasien/catat'
    | '/pasien/edukasi'
    | '/pasien/konsultasi'
    | '/pasien/logbook'
    | '/pasien/obat'
    | '/pasien/profil'
    | '/pasien/riwayat'
    | '/api/public/provision-accounts'
    | '/admin'
    | '/apoteker'
    | '/pasien'
    | '/admin/backup/riwayat'
    | '/admin/pasien-skrining/$id'
    | '/apoteker/pasien/$id'
    | '/api/public/hooks/auto-backup'
    | '/api/public/hooks/mark-missed'
    | '/api/public/hooks/medication-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/apoteker'
    | '/_authenticated/pasien'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/obat'
    | '/_authenticated/admin/skrining'
    | '/_authenticated/admin/users'
    | '/_authenticated/apoteker/edukasi'
    | '/_authenticated/apoteker/kepatuhan'
    | '/_authenticated/apoteker/konsultasi'
    | '/_authenticated/apoteker/obat'
    | '/_authenticated/apoteker/pasien'
    | '/_authenticated/pasien/catat'
    | '/_authenticated/pasien/edukasi'
    | '/_authenticated/pasien/konsultasi'
    | '/_authenticated/pasien/logbook'
    | '/_authenticated/pasien/obat'
    | '/_authenticated/pasien/profil'
    | '/_authenticated/pasien/riwayat'
    | '/api/public/provision-accounts'
    | '/_authenticated/admin/'
    | '/_authenticated/apoteker/'
    | '/_authenticated/pasien/'
    | '/_authenticated/admin/backup/riwayat'
    | '/_authenticated/admin/pasien-skrining/$id'
    | '/_authenticated/apoteker/pasien/$id'
    | '/api/public/hooks/auto-backup'
    | '/api/public/hooks/mark-missed'
    | '/api/public/hooks/medication-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicProvisionAccountsRoute: typeof ApiPublicProvisionAccountsRoute
  ApiPublicHooksAutoBackupRoute: typeof ApiPublicHooksAutoBackupRoute
  ApiPublicHooksMarkMissedRoute: typeof ApiPublicHooksMarkMissedRoute
  ApiPublicHooksMedicationRemindersRoute: typeof ApiPublicHooksMedicationRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apoteker': {
      id: '/_authenticated/apoteker'
      path: '/apoteker'
      fullPath: '/apoteker'
      preLoaderRoute: typeof AuthenticatedApotekerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pasien': {
      id: '/_authenticated/pasien'
      path: '/pasien'
      fullPath: '/pasien'
      preLoaderRoute: typeof AuthenticatedPasienRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/obat': {
      id: '/_authenticated/admin/obat'
      path: '/obat'
      fullPath: '/admin/obat'
      preLoaderRoute: typeof AuthenticatedAdminObatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/skrining': {
      id: '/_authenticated/admin/skrining'
      path: '/skrining'
      fullPath: '/admin/skrining'
      preLoaderRoute: typeof AuthenticatedAdminSkriningRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/apoteker/': {
      id: '/_authenticated/apoteker/'
      path: '/'
      fullPath: '/apoteker/'
      preLoaderRoute: typeof AuthenticatedApotekerIndexRouteImport
      parentRoute: typeof AuthenticatedApotekerRoute
    }
    '/_authenticated/apoteker/edukasi': {
      id: '/_authenticated/apoteker/edukasi'
      path: '/edukasi'
      fullPath: '/apoteker/edukasi'
      preLoaderRoute: typeof AuthenticatedApotekerEdukasiRouteImport
      parentRoute: typeof AuthenticatedApotekerRoute
    }
    '/_authenticated/apoteker/kepatuhan': {
      id: '/_authenticated/apoteker/kepatuhan'
      path: '/kepatuhan'
      fullPath: '/apoteker/kepatuhan'
      preLoaderRoute: typeof AuthenticatedApotekerKepatuhanRouteImport
      parentRoute: typeof AuthenticatedApotekerRoute
    }
    '/_authenticated/apoteker/konsultasi': {
      id: '/_authenticated/apoteker/konsultasi'
      path: '/konsultasi'
      fullPath: '/apoteker/konsultasi'
      preLoaderRoute: typeof AuthenticatedApotekerKonsultasiRouteImport
      parentRoute: typeof AuthenticatedApotekerRoute
    }
    '/_authenticated/apoteker/obat': {
      id: '/_authenticated/apoteker/obat'
      path: '/obat'
      fullPath: '/apoteker/obat'
      preLoaderRoute: typeof AuthenticatedApotekerObatRouteImport
      parentRoute: typeof AuthenticatedApotekerRoute
    }
    '/_authenticated/apoteker/pasien': {
      id: '/_authenticated/apoteker/pasien'
      path: '/pasien'
      fullPath: '/apoteker/pasien'
      preLoaderRoute: typeof AuthenticatedApotekerPasienRouteImport
      parentRoute: typeof AuthenticatedApotekerRoute
    }
    '/_authenticated/pasien/': {
      id: '/_authenticated/pasien/'
      path: '/'
      fullPath: '/pasien/'
      preLoaderRoute: typeof AuthenticatedPasienIndexRouteImport
      parentRoute: typeof AuthenticatedPasienRoute
    }
    '/_authenticated/pasien/catat': {
      id: '/_authenticated/pasien/catat'
      path: '/catat'
      fullPath: '/pasien/catat'
      preLoaderRoute: typeof AuthenticatedPasienCatatRouteImport
      parentRoute: typeof AuthenticatedPasienRoute
    }
    '/_authenticated/pasien/edukasi': {
      id: '/_authenticated/pasien/edukasi'
      path: '/edukasi'
      fullPath: '/pasien/edukasi'
      preLoaderRoute: typeof AuthenticatedPasienEdukasiRouteImport
      parentRoute: typeof AuthenticatedPasienRoute
    }
    '/_authenticated/pasien/konsultasi': {
      id: '/_authenticated/pasien/konsultasi'
      path: '/konsultasi'
      fullPath: '/pasien/konsultasi'
      preLoaderRoute: typeof AuthenticatedPasienKonsultasiRouteImport
      parentRoute: typeof AuthenticatedPasienRoute
    }
    '/_authenticated/pasien/logbook': {
      id: '/_authenticated/pasien/logbook'
      path: '/logbook'
      fullPath: '/pasien/logbook'
      preLoaderRoute: typeof AuthenticatedPasienLogbookRouteImport
      parentRoute: typeof AuthenticatedPasienRoute
    }
    '/_authenticated/pasien/obat': {
      id: '/_authenticated/pasien/obat'
      path: '/obat'
      fullPath: '/pasien/obat'
      preLoaderRoute: typeof AuthenticatedPasienObatRouteImport
      parentRoute: typeof AuthenticatedPasienRoute
    }
    '/_authenticated/pasien/profil': {
      id: '/_authenticated/pasien/profil'
      path: '/profil'
      fullPath: '/pasien/profil'
      preLoaderRoute: typeof AuthenticatedPasienProfilRouteImport
      parentRoute: typeof AuthenticatedPasienRoute
    }
    '/_authenticated/pasien/riwayat': {
      id: '/_authenticated/pasien/riwayat'
      path: '/riwayat'
      fullPath: '/pasien/riwayat'
      preLoaderRoute: typeof AuthenticatedPasienRiwayatRouteImport
      parentRoute: typeof AuthenticatedPasienRoute
    }
    '/api/public/provision-accounts': {
      id: '/api/public/provision-accounts'
      path: '/api/public/provision-accounts'
      fullPath: '/api/public/provision-accounts'
      preLoaderRoute: typeof ApiPublicProvisionAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/backup/riwayat': {
      id: '/_authenticated/admin/backup/riwayat'
      path: '/riwayat'
      fullPath: '/admin/backup/riwayat'
      preLoaderRoute: typeof AuthenticatedAdminBackupRiwayatRouteImport
      parentRoute: typeof AuthenticatedAdminBackupRoute
    }
    '/_authenticated/admin/pasien-skrining/$id': {
      id: '/_authenticated/admin/pasien-skrining/$id'
      path: '/pasien-skrining/$id'
      fullPath: '/admin/pasien-skrining/$id'
      preLoaderRoute: typeof AuthenticatedAdminPasienSkriningIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/apoteker/pasien/$id': {
      id: '/_authenticated/apoteker/pasien/$id'
      path: '/$id'
      fullPath: '/apoteker/pasien/$id'
      preLoaderRoute: typeof AuthenticatedApotekerPasienIdRouteImport
      parentRoute: typeof AuthenticatedApotekerPasienRoute
    }
    '/api/public/hooks/auto-backup': {
      id: '/api/public/hooks/auto-backup'
      path: '/api/public/hooks/auto-backup'
      fullPath: '/api/public/hooks/auto-backup'
      preLoaderRoute: typeof ApiPublicHooksAutoBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mark-missed': {
      id: '/api/public/hooks/mark-missed'
      path: '/api/public/hooks/mark-missed'
      fullPath: '/api/public/hooks/mark-missed'
      preLoaderRoute: typeof ApiPublicHooksMarkMissedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/medication-reminders': {
      id: '/api/public/hooks/medication-reminders'
      path: '/api/public/hooks/medication-reminders'
      fullPath: '/api/public/hooks/medication-reminders'
      preLoaderRoute: typeof ApiPublicHooksMedicationRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminBackupRouteChildren {
  AuthenticatedAdminBackupRiwayatRoute: typeof AuthenticatedAdminBackupRiwayatRoute
}

const AuthenticatedAdminBackupRouteChildren: AuthenticatedAdminBackupRouteChildren =
  {
    AuthenticatedAdminBackupRiwayatRoute: AuthenticatedAdminBackupRiwayatRoute,
  }

const AuthenticatedAdminBackupRouteWithChildren =
  AuthenticatedAdminBackupRoute._addFileChildren(
    AuthenticatedAdminBackupRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRouteWithChildren
  AuthenticatedAdminObatRoute: typeof AuthenticatedAdminObatRoute
  AuthenticatedAdminSkriningRoute: typeof AuthenticatedAdminSkriningRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPasienSkriningIdRoute: typeof AuthenticatedAdminPasienSkriningIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRouteWithChildren,
  AuthenticatedAdminObatRoute: AuthenticatedAdminObatRoute,
  AuthenticatedAdminSkriningRoute: AuthenticatedAdminSkriningRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPasienSkriningIdRoute:
    AuthenticatedAdminPasienSkriningIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedApotekerPasienRouteChildren {
  AuthenticatedApotekerPasienIdRoute: typeof AuthenticatedApotekerPasienIdRoute
}

const AuthenticatedApotekerPasienRouteChildren: AuthenticatedApotekerPasienRouteChildren =
  {
    AuthenticatedApotekerPasienIdRoute: AuthenticatedApotekerPasienIdRoute,
  }

const AuthenticatedApotekerPasienRouteWithChildren =
  AuthenticatedApotekerPasienRoute._addFileChildren(
    AuthenticatedApotekerPasienRouteChildren,
  )

interface AuthenticatedApotekerRouteChildren {
  AuthenticatedApotekerEdukasiRoute: typeof AuthenticatedApotekerEdukasiRoute
  AuthenticatedApotekerKepatuhanRoute: typeof AuthenticatedApotekerKepatuhanRoute
  AuthenticatedApotekerKonsultasiRoute: typeof AuthenticatedApotekerKonsultasiRoute
  AuthenticatedApotekerObatRoute: typeof AuthenticatedApotekerObatRoute
  AuthenticatedApotekerPasienRoute: typeof AuthenticatedApotekerPasienRouteWithChildren
  AuthenticatedApotekerIndexRoute: typeof AuthenticatedApotekerIndexRoute
}

const AuthenticatedApotekerRouteChildren: AuthenticatedApotekerRouteChildren = {
  AuthenticatedApotekerEdukasiRoute: AuthenticatedApotekerEdukasiRoute,
  AuthenticatedApotekerKepatuhanRoute: AuthenticatedApotekerKepatuhanRoute,
  AuthenticatedApotekerKonsultasiRoute: AuthenticatedApotekerKonsultasiRoute,
  AuthenticatedApotekerObatRoute: AuthenticatedApotekerObatRoute,
  AuthenticatedApotekerPasienRoute:
    AuthenticatedApotekerPasienRouteWithChildren,
  AuthenticatedApotekerIndexRoute: AuthenticatedApotekerIndexRoute,
}

const AuthenticatedApotekerRouteWithChildren =
  AuthenticatedApotekerRoute._addFileChildren(
    AuthenticatedApotekerRouteChildren,
  )

interface AuthenticatedPasienRouteChildren {
  AuthenticatedPasienCatatRoute: typeof AuthenticatedPasienCatatRoute
  AuthenticatedPasienEdukasiRoute: typeof AuthenticatedPasienEdukasiRoute
  AuthenticatedPasienKonsultasiRoute: typeof AuthenticatedPasienKonsultasiRoute
  AuthenticatedPasienLogbookRoute: typeof AuthenticatedPasienLogbookRoute
  AuthenticatedPasienObatRoute: typeof AuthenticatedPasienObatRoute
  AuthenticatedPasienProfilRoute: typeof AuthenticatedPasienProfilRoute
  AuthenticatedPasienRiwayatRoute: typeof AuthenticatedPasienRiwayatRoute
  AuthenticatedPasienIndexRoute: typeof AuthenticatedPasienIndexRoute
}

const AuthenticatedPasienRouteChildren: AuthenticatedPasienRouteChildren = {
  AuthenticatedPasienCatatRoute: AuthenticatedPasienCatatRoute,
  AuthenticatedPasienEdukasiRoute: AuthenticatedPasienEdukasiRoute,
  AuthenticatedPasienKonsultasiRoute: AuthenticatedPasienKonsultasiRoute,
  AuthenticatedPasienLogbookRoute: AuthenticatedPasienLogbookRoute,
  AuthenticatedPasienObatRoute: AuthenticatedPasienObatRoute,
  AuthenticatedPasienProfilRoute: AuthenticatedPasienProfilRoute,
  AuthenticatedPasienRiwayatRoute: AuthenticatedPasienRiwayatRoute,
  AuthenticatedPasienIndexRoute: AuthenticatedPasienIndexRoute,
}

const AuthenticatedPasienRouteWithChildren =
  AuthenticatedPasienRoute._addFileChildren(AuthenticatedPasienRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedApotekerRoute: typeof AuthenticatedApotekerRouteWithChildren
  AuthenticatedPasienRoute: typeof AuthenticatedPasienRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedApotekerRoute: AuthenticatedApotekerRouteWithChildren,
  AuthenticatedPasienRoute: AuthenticatedPasienRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicProvisionAccountsRoute: ApiPublicProvisionAccountsRoute,
  ApiPublicHooksAutoBackupRoute: ApiPublicHooksAutoBackupRoute,
  ApiPublicHooksMarkMissedRoute: ApiPublicHooksMarkMissedRoute,
  ApiPublicHooksMedicationRemindersRoute:
    ApiPublicHooksMedicationRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
